theme = "rose_pine_custom"

[editor]
line-number = "relative"
cursorline = true
popup-border = "popup"

[editor.statusline]
left = [
  "mode",
  "spinner",
  # added to defaults
  "version-control",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator"
]

[editor.file-picker]
hidden = false

[keys.insert]
C-c = "normal_mode"

[keys.normal]
C-c = ["keep_primary_selection", "collapse_selection"]
X = "extend_line_above"
A-x = "extend_to_line_bounds"

[keys.select]
C-c = ["normal_mode", "keep_primary_selection", "collapse_selection"]
X = "extend_line_above"
A-x = "extend_to_line_bounds"
