[language-server.zls]
config = { enable_argument_placeholders = false }

[[language]]
name = "c"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[language-server.clangd]
args = [ "--function-arg-placeholders=0" ]

[[language]]
name = "bash"
file-types = [ "sh", "bash", "zsh", "zshrc", { glob = ".zshrc_*" } ]
